# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 00:51
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='exceonum',
        ),
        migrations.AlterField(
            model_name='function_element',
            name='upadetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 8, 51, 29, 973063), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 8, 51, 29, 972063), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='jiekoudeail',
            name='useuser',
            field=models.CharField(max_length=64, null=True, verbose_name='使用'),
        ),
        migrations.AlterField(
            model_name='newusers',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
    ]
