# Generated by Django 3.2.6 on 2021-08-21 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_functionallofic_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 21, 15, 42, 49, 709258), verbose_name='更新时间'),
        ),
    ]
