# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 02:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180510_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function_element',
            name='creat',
        ),
        migrations.RemoveField(
            model_name='function_element',
            name='upade',
        ),
        migrations.RemoveField(
            model_name='function_element',
            name='upadetime',
        ),
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 11, 10, 11, 39, 420314), verbose_name='更新时间'),
        ),
        migrations.RemoveField(
            model_name='project_user',
            name='productname',
        ),
        migrations.AddField(
            model_name='project_user',
            name='productname',
            field=models.ManyToManyField(null=True, to='app.Project'),
        ),
        migrations.AlterField(
            model_name='project_user',
            name='username',
            field=models.CharField(max_length=128, verbose_name='用户'),
        ),
    ]
