# Generated by Django 3.2.6 on 2022-05-29 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_functionallofic_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timmingtask',
            name='tasktyped',
            field=models.CharField(default='一次性任务', max_length=32, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 10, 10, 40, 782871), verbose_name='更新时间'),
        ),
    ]
