# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 08:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180515_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_xing',
            name='functionluo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.FunctionalLofic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 16, 19, 53, 720295), verbose_name='更新时间'),
        ),
    ]
