# Generated by Django 3.2.6 on 2022-05-29 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220529_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='timmingtask',
            name='casetype',
            field=models.CharField(default='UIcase', max_length=32, verbose_name='用例类型'),
        ),
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 12, 37, 55, 258273), verbose_name='更新时间'),
        ),
    ]
