# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-17 08:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180516_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 16, 0, 43, 578314), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='makeuser',
            field=models.ForeignKey(max_length=16, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test_xing',
            name='functionluo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FunctionalLofic'),
        ),
    ]
