# Generated by Django 3.2.6 on 2022-05-29 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220529_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 13, 43, 58, 62863), verbose_name='更新时间'),
        ),
    ]
