# Generated by Django 3.2.6 on 2022-06-03 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_functionallofic_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timmingtask',
            name='apkfilepath',
            field=models.CharField(default=1, max_length=32, verbose_name='测试apk路径'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 15, 1, 3, 622813), verbose_name='更新时间'),
        ),
    ]
