# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-17 08:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180517_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.CharField(max_length=255, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 16, 5, 28, 574614), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='makeuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
