# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-18 06:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180517_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 14, 8, 18, 14640), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='project_user',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
