# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-18 06:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180518_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 14, 8, 30, 27327), verbose_name='更新时间'),
        ),
    ]
