# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-06 23:20
from __future__ import unicode_literals

import datetime
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180518_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('tasktype', models.IntegerField(blank=True, default=0, null=True, verbose_name='任务状态')),
                ('taskiphonetype', models.CharField(default='android', max_length=8, verbose_name='任务设备')),
                ('project', models.IntegerField(blank=True, verbose_name='执行设备数')),
                ('runphonenum', models.IntegerField(blank=True, default=1, null=True, verbose_name='执行设备数')),
                ('iscollectperformncedata', models.BooleanField(default=True, verbose_name='是否收集性能数据')),
            ],
            options={
                'verbose_name': '任务列表',
                'verbose_name_plural': '任务列表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TasklistCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('task', models.IntegerField(blank=True, null=True, verbose_name='执行任务')),
                ('caserun', models.IntegerField(blank=True, null=True, verbose_name='执行caseID')),
            ],
            options={
                'verbose_name': '任务用例表',
                'verbose_name_plural': '任务用例表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TasklistTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('task', models.IntegerField(blank=True, null=True, verbose_name='执行任务')),
                ('taskrun', models.IntegerField(blank=True, null=True, verbose_name='执行任务ID')),
            ],
            options={
                'verbose_name': '任务定时任务表',
                'verbose_name_plural': '任务定时任务表',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 7, 20, 1, 567744), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='newusers',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
