# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-07 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201107_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='tasklisttype',
            field=models.IntegerField(blank=True, default=0, verbose_name='任务列表的类型'),
        ),
        migrations.AlterField(
            model_name='functionallofic',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 17, 6, 31, 490321), verbose_name='更新时间'),
        ),
    ]
